version: '3.8'

services:
  db:
    restart: always
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=accounting
    volumes:
      - workplace:/var/lib/postgresql/data

  server:
    depends_on:
      - db
    build:
      context: ./
      dockerfile: docker/server/Dockerfile
    ports:
      - "9090:9090"
    environment:
      PORT: "9090"
      DATABASE_URL: "postgres://postgres:postgres@db/accounting?sslmode=disable"
      PG_MIGRATIONS_PATH: "file://../../internal/pg/migrations"
    command: [ "./../../wait-for-it.sh", "db:5432", "--timeout=60", "--", "./server" ]

volumes:
  workplace:
