version: '3.8'

services:

  postgres:
    restart: always
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=accounting
    volumes:
      - workplace:/var/lib/postgresql/data

  accounting_server:
    depends_on:
      - postgres
    build:
      context: ./
      dockerfile: docker/server/Dockerfile
    container_name: server
    ports:
     - "9090:9090"
    environment:
      PORT: "9090"
      PG_URL: "postgres://postgres:postgres@postgres/accounting?sslmode=disable"
      PG_MIGRATIONS_PATH: "file://../../internal/pg/migrations"

    command: ["./../../wait-for-it.sh", "postgres:5432", "--timeout=60", "--", "./server"]

volumes:
  workplace:
